name: Run Unit Tests

on: [push]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 #Baixa o código
        working-directory: ./nestjs-kingdoms-of-vallor
      - uses: actions/setup-node@v3 #Configura o node
        with:
          node-version: 18
          cache: 'yarn'

      - run: yarn install --frozen-lockfile #Não interativo

      - run: yarn test
