name: Run Unit Tests

on: [push]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 #Baixa o código
      - uses: actions/setup-node@v3 #Configura o node
        with:
          node-version: 18
          cache: 'yarn'

      -  run: |
          cd nestjs-kingdoms-of-vallor
          yarn install --frozen-lockfile

      - run: |
          cd nestjs-kingdoms-of-vallor
          yarn test
