name: Run Unit Tests

on: [push]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'nestjs-kingdoms-of-vallor'

    steps:
      - uses: actions/checkout@v3 #Baixa o código
      - uses: actions/setup-node@v3 #Configura o node
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Tests
        run: yarn test
